#!/usr/bin/php
<?php
function sendGCM($id) {


    $url = 'https://fcm.googleapis.com/fcm/send';

    $fields = array (
            'registration_ids' => array (
                    $id
            ),
            "data"    => [
			    "data"  => [
			      "alert"     => "Testing " . time(),
			      "title"     => "The title",
			      "vibrate"   => [100,50,50,50,100],
			      "badge"     => 1,
			      "tag"       => "APP"
			    ]
			  ]
    );
    $fields = json_encode ( $fields );

    $headers = array (
            'Authorization: key=' . "<AUTH KEY>",
            'Content-Type: application/json'
    );

    $ch = curl_init ();
    curl_setopt ( $ch, CURLOPT_URL, $url );
    curl_setopt ( $ch, CURLOPT_POST, true );
    curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
    curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
    curl_setopt ( $ch, CURLOPT_POSTFIELDS, $fields );

    $result = curl_exec ( $ch );
    echo $result;
    curl_close ( $ch );
}

sendGCM("DEVICE TOKEN");